#!/bin/bash
#

STATSMPFILE="/tmp/rndcstatus.tmp"

zones=`cat ${STATSMPFILE}|grep "number of zones:"|awk -F":" '{print $2}'|sed 's/\s//g'`
xfersrunning=`cat ${STATSMPFILE}|grep "xfers running:"|awk -F":" '{print $2}'|sed 's/\s//g'`
xfersdeferred=`cat ${STATSMPFILE}|grep "xfers deferred:"|awk -F":" '{print $2}'|sed 's/\s//g'`
soaqueriesinprogress=`cat ${STATSMPFILE}|grep "soa queries in progress:"|awk -F":" '{print $2}'|sed 's/\s//g'`
recursiveclient=`cat ${STATSMPFILE}|grep "recursive clients:"|awk -F":" '{print $2}'|awk -F"/" '{print $1}'|sed 's/\s//g'`
recursiveclientmax=`cat ${STATSMPFILE}|grep "recursive clients:"|awk -F":" '{print $2}'|awk -F"/" '{print $3}'|sed 's/\s//g'`
tcpclient=`cat ${STATSMPFILE}|grep "tcp clients:"|awk -F":" '{print $2}'|awk -F"/" '{print $1}'|sed 's/\s//g'`
tcpclientmax=`cat ${STATSMPFILE}|grep "tcp clients:"|awk -F":" '{print $2}'|awk -F"/" '{print $2}'|sed 's/\s//g'`

echo "zones:${zones} xfersrunning:${xfersrunning} xfersdeferred:${xfersdeferred} soaqueriesinprogress:${soaqueriesinprogress} recursiveclient:${recursiveclient} recursiveclientmax:${recursiveclientmax}  tcpclient:${tcpclient}  tcpclientmax:${tcpclientmax}"
